/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../components/layout';
import * as import12 from '../components/sidenav';
import * as import13 from '../components/nav-item';
import * as import14 from '@angular/router/src/directives/router_link';
import * as import15 from '../components/toolbar';
import * as import16 from '@angular/router/src/directives/router_outlet';
import * as import17 from '@angular/common/src/pipes/async_pipe';
import * as import18 from '../components/layout.ngfactory';
import * as import19 from '../components/sidenav.ngfactory';
import * as import20 from '../components/nav-item.ngfactory';
import * as import21 from '@angular/router/src/router';
import * as import22 from '@angular/router/src/router_state';
import * as import23 from '@angular/common/src/location/location_strategy';
import * as import24 from '../components/toolbar.ngfactory';
import * as import25 from '@angular/router/src/router_outlet_map';
import * as import26 from '@angular/core/src/linker/component_factory_resolver';
var renderType_AppComponent_Host:import0.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AppComponent_0_4:import3.AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('book-collection-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import3.AppComponent(this.parentInjector.get(import8.Store));
    this._appEl_0.initComponent(this._AppComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import10.ComponentFactory<import3.AppComponent> = new import10.ComponentFactory<import3.AppComponent>('book-collection-app',viewFactory_AppComponent_Host0,import3.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import0.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import3.AppComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _LayoutComponent_1_4:import11.LayoutComponent;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _SidenavComponent_3_4:import12.SidenavComponent;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _NavItemComponent_5_4:import13.NavItemComponent;
  _RouterLink_5_5:import14.RouterLink;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _NavItemComponent_8_4:import13.NavItemComponent;
  _RouterLink_8_5:import14.RouterLink;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _ToolbarComponent_12_4:import15.ToolbarComponent;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _RouterOutlet_15_5:import16.RouterOutlet;
  _text_16:any;
  _text_17:any;
  _pipe_async_0:import17.AsyncPipe;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'bc-layout',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import18.viewFactory_LayoutComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._LayoutComponent_1_4 = new import11.LayoutComponent();
    this._appEl_1.initComponent(this._LayoutComponent_1_4,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'bc-sidenav',(null as any));
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import19.viewFactory_SidenavComponent0(this.viewUtils,this.injector(3),this._appEl_3);
    this._SidenavComponent_3_4 = new import12.SidenavComponent();
    this._appEl_3.initComponent(this._SidenavComponent_3_4,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'bc-nav-item',(null as any));
    this.renderer.setElementAttribute(this._el_5,'hint','View your book collection');
    this.renderer.setElementAttribute(this._el_5,'icon','book');
    this.renderer.setElementAttribute(this._el_5,'routerLink','/');
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import20.viewFactory_NavItemComponent0(this.viewUtils,this.injector(5),this._appEl_5);
    this._NavItemComponent_5_4 = new import13.NavItemComponent();
    this._RouterLink_5_5 = new import14.RouterLink(this.parentInjector.get(import21.Router),this.parentInjector.get(import22.ActivatedRoute),this.parentInjector.get(import23.LocationStrategy));
    this._appEl_5.initComponent(this._NavItemComponent_5_4,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n          My Collection\n        ',(null as any));
    compView_5.create(this._NavItemComponent_5_4,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'bc-nav-item',(null as any));
    this.renderer.setElementAttribute(this._el_8,'hint','Find your next book!');
    this.renderer.setElementAttribute(this._el_8,'icon','search');
    this.renderer.setElementAttribute(this._el_8,'routerLink','/book/find');
    this._appEl_8 = new import2.AppElement(8,3,this,this._el_8);
    var compView_8:any = import20.viewFactory_NavItemComponent0(this.viewUtils,this.injector(8),this._appEl_8);
    this._NavItemComponent_8_4 = new import13.NavItemComponent();
    this._RouterLink_8_5 = new import14.RouterLink(this.parentInjector.get(import21.Router),this.parentInjector.get(import22.ActivatedRoute),this.parentInjector.get(import23.LocationStrategy));
    this._appEl_8.initComponent(this._NavItemComponent_8_4,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n          Browse Books\n        ',(null as any));
    compView_8.create(this._NavItemComponent_8_4,[([] as any[]).concat([this._text_9])],(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_3.create(this._SidenavComponent_3_4,[([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7,
        this._el_8,
        this._text_10
      ]
    )],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'bc-toolbar',(null as any));
    this._appEl_12 = new import2.AppElement(12,1,this,this._el_12);
    var compView_12:any = import24.viewFactory_ToolbarComponent0(this.viewUtils,this.injector(12),this._appEl_12);
    this._ToolbarComponent_12_4 = new import15.ToolbarComponent();
    this._appEl_12.initComponent(this._ToolbarComponent_12_4,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n        Book Collection\n      ',(null as any));
    compView_12.create(this._ToolbarComponent_12_4,[([] as any[]).concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n\n      ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'router-outlet',(null as any));
    this._appEl_15 = new import2.AppElement(15,1,this,this._el_15);
    this._RouterOutlet_15_5 = new import16.RouterOutlet(this.parentInjector.get(import25.RouterOutletMap),this._appEl_15.vcRef,this.parentInjector.get(import26.ComponentFactoryResolver),(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_1.create(this._LayoutComponent_1_4,[([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_11,
        this._el_12,
        this._text_14,
        this._appEl_15,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._pipe_async_0 = new import17.AsyncPipe(this.ref);
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'activate',this.eventHandler(this._handle_activate_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NavItemComponent_5_4.activate.subscribe(this.eventHandler(this._handle_activate_5_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_8,'activate',this.eventHandler(this._handle_activate_8_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_1.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    const subscription_1:any = this._NavItemComponent_8_4.activate.subscribe(this.eventHandler(this._handle_activate_8_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_12,'openMenu',this.eventHandler(this._handle_openMenu_12_0.bind(this)));
    const subscription_2:any = this._ToolbarComponent_12_4.openMenu.subscribe(this.eventHandler(this._handle_openMenu_12_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.NavItemComponent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._NavItemComponent_5_4; }
    if (((token === import14.RouterLink) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLink_5_5; }
    if (((token === import13.NavItemComponent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NavItemComponent_8_4; }
    if (((token === import14.RouterLink) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLink_8_5; }
    if (((token === import12.SidenavComponent) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._SidenavComponent_3_4; }
    if (((token === import15.ToolbarComponent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarComponent_12_4; }
    if (((token === import16.RouterOutlet) && (15 === requestNodeIndex))) { return this._RouterOutlet_15_5; }
    if (((token === import11.LayoutComponent) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._LayoutComponent_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.showSidenav$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this._SidenavComponent_3_4.open = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = 'book';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NavItemComponent_5_4.icon = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = 'View your book collection';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NavItemComponent_5_4.hint = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NavItemComponent_5_4.routerLink = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._RouterLink_5_5.routerLink = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = 'search';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NavItemComponent_8_4.icon = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = 'Find your next book!';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NavItemComponent_8_4.hint = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = '/book/find';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NavItemComponent_8_4.routerLink = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = '/book/find';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RouterLink_8_5.routerLink = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_15_5.ngOnDestroy();
    this._pipe_async_0.ngOnDestroy();
  }
  private _handle_activate_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.closeSidenav()) !== false);
    return (true && pd_0);
  }
  private _handle_click_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLink_5_5.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_activate_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.closeSidenav()) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLink_8_5.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_openMenu_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.openSidenav()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}