/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './collection-page';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/material/card/card';
import * as import12 from '../components/book-preview-list';
import * as import13 from '@angular/common/src/pipes/async_pipe';
import * as import14 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import15 from '../components/book-preview-list.ngfactory';
var renderType_CollectionPageComponent_Host:import0.RenderComponentType = (null as any);
class _View_CollectionPageComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CollectionPageComponent_0_4:import3.CollectionPageComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CollectionPageComponent_Host0,renderType_CollectionPageComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-collection-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CollectionPageComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CollectionPageComponent_0_4 = new import3.CollectionPageComponent(this.parentInjector.get(import8.Store));
    this._appEl_0.initComponent(this._CollectionPageComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._CollectionPageComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CollectionPageComponent) && (0 === requestNodeIndex))) { return this._CollectionPageComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CollectionPageComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CollectionPageComponent_Host === (null as any))) { (renderType_CollectionPageComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_CollectionPageComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CollectionPageComponentNgFactory:import10.ComponentFactory<import3.CollectionPageComponent> = new import10.ComponentFactory<import3.CollectionPageComponent>('bc-collection-page',viewFactory_CollectionPageComponent_Host0,import3.CollectionPageComponent);
const styles_CollectionPageComponent:any[] = ['md-card-title[_ngcontent-%COMP%] {\n      display: flex;\n      justify-content: center;\n    }'];
var renderType_CollectionPageComponent:import0.RenderComponentType = (null as any);
class _View_CollectionPageComponent0 extends import1.AppView<import3.CollectionPageComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _MdCard_1_4:import11.MdCard;
  _text_2:any;
  _el_3:any;
  _MdCardTitle_3_3:import11.MdCardTitle;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _BookPreviewListComponent_7_4:import12.BookPreviewListComponent;
  _text_8:any;
  _pipe_async_0:import13.AsyncPipe;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CollectionPageComponent0,renderType_CollectionPageComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'md-card',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import14.viewFactory_MdCard0(this.viewUtils,this.injector(1),this._appEl_1);
    this._MdCard_1_4 = new import11.MdCard();
    this._appEl_1.initComponent(this._MdCard_1_4,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'md-card-title',(null as any));
    this._MdCardTitle_3_3 = new import11.MdCardTitle();
    this._text_4 = this.renderer.createText(this._el_3,'My Collection',(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_1.create(this._MdCard_1_4,[([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'bc-book-preview-list',(null as any));
    this._appEl_7 = new import2.AppElement(7,(null as any),this,this._el_7);
    var compView_7:any = import15.viewFactory_BookPreviewListComponent0(this.viewUtils,this.injector(7),this._appEl_7);
    this._BookPreviewListComponent_7_4 = new import12.BookPreviewListComponent();
    this._appEl_7.initComponent(this._BookPreviewListComponent_7_4,([] as any[]),compView_7);
    compView_7.create(this._BookPreviewListComponent_7_4,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._pipe_async_0 = new import13.AsyncPipe(this.ref);
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdCardTitle) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdCardTitle_3_3; }
    if (((token === import11.MdCard) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdCard_1_4; }
    if (((token === import12.BookPreviewListComponent) && (7 === requestNodeIndex))) { return this._BookPreviewListComponent_7_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.books$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this._BookPreviewListComponent_7_4.books = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
}
export function viewFactory_CollectionPageComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CollectionPageComponent> {
  if ((renderType_CollectionPageComponent === (null as any))) { (renderType_CollectionPageComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_CollectionPageComponent,{})); }
  return new _View_CollectionPageComponent0(viewUtils,parentInjector,declarationEl);
}