/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './find-book-page';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../components/book-search';
import * as import12 from '../components/book-preview-list';
import * as import13 from '@angular/common/src/pipes/async_pipe';
import * as import14 from '../components/book-search.ngfactory';
import * as import15 from '../components/book-preview-list.ngfactory';
var renderType_FindBookPageComponent_Host:import0.RenderComponentType = (null as any);
class _View_FindBookPageComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FindBookPageComponent_0_4:import3.FindBookPageComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FindBookPageComponent_Host0,renderType_FindBookPageComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-find-book-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FindBookPageComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FindBookPageComponent_0_4 = new import3.FindBookPageComponent(this.parentInjector.get(import8.Store));
    this._appEl_0.initComponent(this._FindBookPageComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._FindBookPageComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FindBookPageComponent) && (0 === requestNodeIndex))) { return this._FindBookPageComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FindBookPageComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FindBookPageComponent_Host === (null as any))) { (renderType_FindBookPageComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_FindBookPageComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const FindBookPageComponentNgFactory:import10.ComponentFactory<import3.FindBookPageComponent> = new import10.ComponentFactory<import3.FindBookPageComponent>('bc-find-book-page',viewFactory_FindBookPageComponent_Host0,import3.FindBookPageComponent);
const styles_FindBookPageComponent:any[] = ([] as any[]);
var renderType_FindBookPageComponent:import0.RenderComponentType = (null as any);
class _View_FindBookPageComponent0 extends import1.AppView<import3.FindBookPageComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _BookSearchComponent_1_4:import11.BookSearchComponent;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _BookPreviewListComponent_3_4:import12.BookPreviewListComponent;
  _text_4:any;
  _pipe_async_0:import13.AsyncPipe;
  /*private*/ _expr_1:any;
  _pipe_async_1:import13.AsyncPipe;
  /*private*/ _expr_2:any;
  _pipe_async_2:import13.AsyncPipe;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FindBookPageComponent0,renderType_FindBookPageComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'bc-book-search',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import14.viewFactory_BookSearchComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._BookSearchComponent_1_4 = new import11.BookSearchComponent();
    this._appEl_1.initComponent(this._BookSearchComponent_1_4,([] as any[]),compView_1);
    compView_1.create(this._BookSearchComponent_1_4,([] as any[]),(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'bc-book-preview-list',(null as any));
    this._appEl_3 = new import2.AppElement(3,(null as any),this,this._el_3);
    var compView_3:any = import15.viewFactory_BookPreviewListComponent0(this.viewUtils,this.injector(3),this._appEl_3);
    this._BookPreviewListComponent_3_4 = new import12.BookPreviewListComponent();
    this._appEl_3.initComponent(this._BookPreviewListComponent_3_4,([] as any[]),compView_3);
    compView_3.create(this._BookPreviewListComponent_3_4,([] as any[]),(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'search',this.eventHandler(this._handle_search_1_0.bind(this)));
    this._pipe_async_0 = new import13.AsyncPipe(this.ref);
    this._expr_1 = import7.UNINITIALIZED;
    this._pipe_async_1 = new import13.AsyncPipe(this.ref);
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._BookSearchComponent_1_4.search.subscribe(this.eventHandler(this._handle_search_1_0.bind(this)));
    this._pipe_async_2 = new import13.AsyncPipe(this.ref);
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.BookSearchComponent) && (1 === requestNodeIndex))) { return this._BookSearchComponent_1_4; }
    if (((token === import12.BookPreviewListComponent) && (3 === requestNodeIndex))) { return this._BookPreviewListComponent_3_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_1:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.searchQuery$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this._BookSearchComponent_1_4.query = currVal_1;
      this._expr_1 = currVal_1;
    }
    valUnwrapper.reset();
    const currVal_2:any = valUnwrapper.unwrap(this._pipe_async_1.transform(this.context.loading$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this._BookSearchComponent_1_4.searching = currVal_2;
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = valUnwrapper.unwrap(this._pipe_async_2.transform(this.context.books$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this._BookPreviewListComponent_3_4.books = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
    this._pipe_async_1.ngOnDestroy();
    this._pipe_async_2.ngOnDestroy();
  }
  private _handle_search_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.search($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FindBookPageComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FindBookPageComponent> {
  if ((renderType_FindBookPageComponent === (null as any))) { (renderType_FindBookPageComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_FindBookPageComponent,{})); }
  return new _View_FindBookPageComponent0(viewUtils,parentInjector,declarationEl);
}