/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './selected-book-page';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../components/book-detail';
import * as import12 from '@angular/common/src/pipes/async_pipe';
import * as import13 from '../components/book-detail.ngfactory';
var renderType_SelectedBookPageComponent_Host:import0.RenderComponentType = (null as any);
class _View_SelectedBookPageComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SelectedBookPageComponent_0_4:import3.SelectedBookPageComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SelectedBookPageComponent_Host0,renderType_SelectedBookPageComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-selected-book-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SelectedBookPageComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SelectedBookPageComponent_0_4 = new import3.SelectedBookPageComponent(this.parentInjector.get(import8.Store));
    this._appEl_0.initComponent(this._SelectedBookPageComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._SelectedBookPageComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SelectedBookPageComponent) && (0 === requestNodeIndex))) { return this._SelectedBookPageComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SelectedBookPageComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SelectedBookPageComponent_Host === (null as any))) { (renderType_SelectedBookPageComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SelectedBookPageComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SelectedBookPageComponentNgFactory:import10.ComponentFactory<import3.SelectedBookPageComponent> = new import10.ComponentFactory<import3.SelectedBookPageComponent>('bc-selected-book-page',viewFactory_SelectedBookPageComponent_Host0,import3.SelectedBookPageComponent);
const styles_SelectedBookPageComponent:any[] = ([] as any[]);
var renderType_SelectedBookPageComponent:import0.RenderComponentType = (null as any);
class _View_SelectedBookPageComponent0 extends import1.AppView<import3.SelectedBookPageComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _BookDetailComponent_1_4:import11.BookDetailComponent;
  _text_2:any;
  _text_3:any;
  _pipe_async_0:import12.AsyncPipe;
  /*private*/ _expr_2:any;
  _pipe_async_1:import12.AsyncPipe;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SelectedBookPageComponent0,renderType_SelectedBookPageComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'bc-book-detail',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import13.viewFactory_BookDetailComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._BookDetailComponent_1_4 = new import11.BookDetailComponent();
    this._appEl_1.initComponent(this._BookDetailComponent_1_4,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_1.create(this._BookDetailComponent_1_4,([] as any[]),(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'add',this.eventHandler(this._handle_add_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_1,'remove',this.eventHandler(this._handle_remove_1_1.bind(this)));
    this._pipe_async_0 = new import12.AsyncPipe(this.ref);
    this._expr_2 = import7.UNINITIALIZED;
    this._pipe_async_1 = new import12.AsyncPipe(this.ref);
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._BookDetailComponent_1_4.add.subscribe(this.eventHandler(this._handle_add_1_0.bind(this)));
    const subscription_1:any = this._BookDetailComponent_1_4.remove.subscribe(this.eventHandler(this._handle_remove_1_1.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.BookDetailComponent) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._BookDetailComponent_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_2:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.book$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this._BookDetailComponent_1_4.book = currVal_2;
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = valUnwrapper.unwrap(this._pipe_async_1.transform(this.context.isSelectedBookInCollection$));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this._BookDetailComponent_1_4.inCollection = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
    this._pipe_async_1.ngOnDestroy();
  }
  private _handle_add_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addToCollection($event)) !== false);
    return (true && pd_0);
  }
  private _handle_remove_1_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.removeFromCollection($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SelectedBookPageComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SelectedBookPageComponent> {
  if ((renderType_SelectedBookPageComponent === (null as any))) { (renderType_SelectedBookPageComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_SelectedBookPageComponent,{})); }
  return new _View_SelectedBookPageComponent0(viewUtils,parentInjector,declarationEl);
}