/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './view-book-page';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@ngrx/store/src/store';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './selected-book-page';
import * as import13 from './selected-book-page.ngfactory';
var renderType_ViewBookPageComponent_Host:import0.RenderComponentType = (null as any);
class _View_ViewBookPageComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ViewBookPageComponent_0_4:import3.ViewBookPageComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ViewBookPageComponent_Host0,renderType_ViewBookPageComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-view-book-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ViewBookPageComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ViewBookPageComponent_0_4 = new import3.ViewBookPageComponent(this.parentInjector.get(import8.Store),this.parentInjector.get(import9.ActivatedRoute));
    this._appEl_0.initComponent(this._ViewBookPageComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._ViewBookPageComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ViewBookPageComponent) && (0 === requestNodeIndex))) { return this._ViewBookPageComponent_0_4; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ViewBookPageComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_ViewBookPageComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ViewBookPageComponent_Host === (null as any))) { (renderType_ViewBookPageComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ViewBookPageComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ViewBookPageComponentNgFactory:import11.ComponentFactory<import3.ViewBookPageComponent> = new import11.ComponentFactory<import3.ViewBookPageComponent>('bc-view-book-page',viewFactory_ViewBookPageComponent_Host0,import3.ViewBookPageComponent);
const styles_ViewBookPageComponent:any[] = ([] as any[]);
var renderType_ViewBookPageComponent:import0.RenderComponentType = (null as any);
class _View_ViewBookPageComponent0 extends import1.AppView<import3.ViewBookPageComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _SelectedBookPageComponent_1_4:import12.SelectedBookPageComponent;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ViewBookPageComponent0,renderType_ViewBookPageComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'bc-selected-book-page',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import13.viewFactory_SelectedBookPageComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._SelectedBookPageComponent_1_4 = new import12.SelectedBookPageComponent(this.parentInjector.get(import8.Store));
    this._appEl_1.initComponent(this._SelectedBookPageComponent_1_4,([] as any[]),compView_1);
    compView_1.create(this._SelectedBookPageComponent_1_4,([] as any[]),(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.SelectedBookPageComponent) && (1 === requestNodeIndex))) { return this._SelectedBookPageComponent_1_4; }
    return notFoundResult;
  }
}
export function viewFactory_ViewBookPageComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ViewBookPageComponent> {
  if ((renderType_ViewBookPageComponent === (null as any))) { (renderType_ViewBookPageComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_ViewBookPageComponent,{})); }
  return new _View_ViewBookPageComponent0(viewUtils,parentInjector,declarationEl);
}