/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './book-preview';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/router/src/directives/router_link';
import * as import11 from '@angular/material/card/card';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from './book-authors';
import * as import14 from '../pipes/ellipsis';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from './book-authors.ngfactory';
import * as import21 from '@angular/core/src/security';
var renderType_BookPreviewComponent_Host:import0.RenderComponentType = (null as any);
class _View_BookPreviewComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BookPreviewComponent_0_4:import3.BookPreviewComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewComponent_Host0,renderType_BookPreviewComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-book-preview',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_BookPreviewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BookPreviewComponent_0_4 = new import3.BookPreviewComponent();
    this._appEl_0.initComponent(this._BookPreviewComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._BookPreviewComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.BookPreviewComponent) && (0 === requestNodeIndex))) { return this._BookPreviewComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_BookPreviewComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_BookPreviewComponent_Host === (null as any))) { (renderType_BookPreviewComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_BookPreviewComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const BookPreviewComponentNgFactory:import9.ComponentFactory<import3.BookPreviewComponent> = new import9.ComponentFactory<import3.BookPreviewComponent>('bc-book-preview',viewFactory_BookPreviewComponent_Host0,import3.BookPreviewComponent);
const styles_BookPreviewComponent:any[] = ['md-card[_ngcontent-%COMP%] {\n      width: 400px;\n      height: 300px;\n      margin: 15px;\n    }\n    md-card-title[_ngcontent-%COMP%] {\n      margin-right: 10px;\n    }\n    a[_ngcontent-%COMP%] {\n      color: inherit;\n      text-decoration: none;\n    }\n    img[_ngcontent-%COMP%] {\n      width: 60px;\n      min-width: 60px;\n      margin-left: 5px;\n    }\n    md-card-content[_ngcontent-%COMP%] {\n      margin-top: 15px;\n    }\n    span[_ngcontent-%COMP%] {\n      display: inline-block;\n      font-size: 13px;\n    }\n    md-card-footer[_ngcontent-%COMP%] {\n      padding: 0 25px 25px;\n    }'];
var renderType_BookPreviewComponent:import0.RenderComponentType = (null as any);
class _View_BookPreviewComponent0 extends import1.AppView<import3.BookPreviewComponent> {
  _text_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import10.RouterLinkWithHref;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _MdCard_3_4:import11.MdCard;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _MdCardTitleGroup_5_4:import11.MdCardTitleGroup;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import12.NgIf;
  _text_8:any;
  _el_9:any;
  _MdCardTitle_9_3:import11.MdCardTitle;
  _text_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import12.NgIf;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _MdCardContent_15_3:import11.MdCardContent;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import12.NgIf;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _MdCardFooter_20_3:import11.MdCardFooter;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _BookAuthorsComponent_22_4:import13.BookAuthorsComponent;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  _pipe_bcEllipsis_0:import14.EllipsisPipe;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewComponent0,renderType_BookPreviewComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import10.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'md-card',(null as any));
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import18.viewFactory_MdCard0(this.viewUtils,this.injector(3),this._appEl_3);
    this._MdCard_3_4 = new import11.MdCard();
    this._appEl_3.initComponent(this._MdCard_3_4,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'md-card-title-group',(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import18.viewFactory_MdCardTitleGroup0(this.viewUtils,this.injector(5),this._appEl_5);
    this._MdCardTitleGroup_5_4 = new import11.MdCardTitleGroup();
    this._appEl_5.initComponent(this._MdCardTitleGroup_5_4,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_7 = new import2.AppElement(7,5,this,this._anchor_7);
    this._TemplateRef_7_5 = new import19.TemplateRef_(this._appEl_7,viewFactory_BookPreviewComponent1);
    this._NgIf_7_6 = new import12.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'md-card-title',(null as any));
    this._MdCardTitle_9_3 = new import11.MdCardTitle();
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_12 = new import2.AppElement(12,5,this,this._anchor_12);
    this._TemplateRef_12_5 = new import19.TemplateRef_(this._appEl_12,viewFactory_BookPreviewComponent2);
    this._NgIf_12_6 = new import12.NgIf(this._appEl_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_5.create(this._MdCardTitleGroup_5_4,[
      ([] as any[]).concat([
        this._el_9,
        this._appEl_12
      ]
      ),
      ([] as any[]).concat([this._appEl_7]),
      ([] as any[]).concat([
        this._text_6,
        this._text_8,
        this._text_11,
        this._text_13
      ]
      )
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'md-card-content',(null as any));
    this._MdCardContent_15_3 = new import11.MdCardContent();
    this._text_16 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_17 = new import2.AppElement(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import19.TemplateRef_(this._appEl_17,viewFactory_BookPreviewComponent3);
    this._NgIf_17_6 = new import12.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'md-card-footer',(null as any));
    this._MdCardFooter_20_3 = new import11.MdCardFooter();
    this._text_21 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'bc-book-authors',(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._el_22);
    var compView_22:any = import20.viewFactory_BookAuthorsComponent0(this.viewUtils,this.injector(22),this._appEl_22);
    this._BookAuthorsComponent_22_4 = new import13.BookAuthorsComponent();
    this._appEl_22.initComponent(this._BookAuthorsComponent_22_4,([] as any[]),compView_22);
    compView_22.create(this._BookAuthorsComponent_22_4,([] as any[]),(null as any));
    this._text_23 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_3.create(this._MdCard_3_4,[([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_14,
        this._el_15,
        this._text_19,
        this._el_20,
        this._text_24
      ]
    )],(null as any));
    this._text_25 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._arr_0 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._pipe_bcEllipsis_0 = new import14.EllipsisPipe();
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import12.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import11.MdCardTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdCardTitle_9_3; }
    if (((token === import19.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import12.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6; }
    if (((token === import11.MdCardTitleGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._MdCardTitleGroup_5_4; }
    if (((token === import19.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import12.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import11.MdCardContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._MdCardContent_15_3; }
    if (((token === import13.BookAuthorsComponent) && (22 === requestNodeIndex))) { return this._BookAuthorsComponent_22_4; }
    if (((token === import11.MdCardFooter) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdCardFooter_20_3; }
    if (((token === import11.MdCard) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._MdCard_3_4; }
    if (((token === import10.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkWithHref_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/book',this.context.id);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    const currVal_3:any = this.context.thumbnail;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_7_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = this.context.subtitle;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_12_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.description;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_17_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.book;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._BookAuthorsComponent_22_4.book = currVal_7;
      this._expr_7 = currVal_7;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_10,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_BookPreviewComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.BookPreviewComponent> {
  if ((renderType_BookPreviewComponent === (null as any))) { (renderType_BookPreviewComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_BookPreviewComponent,{})); }
  return new _View_BookPreviewComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_BookPreviewComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewComponent1,renderType_BookPreviewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'md-card-sm-image','');
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.thumbnail;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_BookPreviewComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_BookPreviewComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_BookPreviewComponent2 extends import1.AppView<any> {
  _el_0:any;
  _MdCardSubtitle_0_3:import11.MdCardSubtitle;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewComponent2,renderType_BookPreviewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'md-card-subtitle',(null as any));
    this._MdCardSubtitle_0_3 = new import11.MdCardSubtitle();
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdCardSubtitle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdCardSubtitle_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.subtitle,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_BookPreviewComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_BookPreviewComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_BookPreviewComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _pipe_bcEllipsis_0_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewComponent3,renderType_BookPreviewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_bcEllipsis_0_0 = import4.pureProxy1((<_View_BookPreviewComponent0>this.parent)._pipe_bcEllipsis_0.transform.bind((<_View_BookPreviewComponent0>this.parent)._pipe_bcEllipsis_0));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_bcEllipsis_0_0,(<_View_BookPreviewComponent0>this.parent)._pipe_bcEllipsis_0.transform)(this.parent.context.description)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_BookPreviewComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_BookPreviewComponent3(viewUtils,parentInjector,declarationEl);
}