/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './book-search';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/material/card/card';
import * as import11 from '@angular/material/input/input';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/material/progress-circle/progress-circle';
import * as import14 from '../../node_modules/@angular/material/card/card.ngfactory';
import * as import15 from '../../node_modules/@angular/material/input/input.ngfactory';
import * as import16 from '../../node_modules/@angular/material/progress-circle/progress-circle.ngfactory';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
var renderType_BookSearchComponent_Host:import0.RenderComponentType = (null as any);
class _View_BookSearchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BookSearchComponent_0_4:import3.BookSearchComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookSearchComponent_Host0,renderType_BookSearchComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-book-search',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_BookSearchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BookSearchComponent_0_4 = new import3.BookSearchComponent();
    this._appEl_0.initComponent(this._BookSearchComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._BookSearchComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.BookSearchComponent) && (0 === requestNodeIndex))) { return this._BookSearchComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_BookSearchComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_BookSearchComponent_Host === (null as any))) { (renderType_BookSearchComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_BookSearchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const BookSearchComponentNgFactory:import9.ComponentFactory<import3.BookSearchComponent> = new import9.ComponentFactory<import3.BookSearchComponent>('bc-book-search',viewFactory_BookSearchComponent_Host0,import3.BookSearchComponent);
const styles_BookSearchComponent:any[] = ['md-card-title[_ngcontent-%COMP%], md-card-content[_ngcontent-%COMP%] {\n      display: flex;\n      justify-content: center;\n    }\n\n    md-input[_ngcontent-%COMP%] {\n      width: 300px;\n    }\n\n    md-card-spinner[_ngcontent-%COMP%] {\n      padding-left: 60px; // Make room for the spinner\n    }\n\n    md-spinner[_ngcontent-%COMP%] {\n      width: 30px;\n      height: 30px;\n      position: relative;\n      top: 10px;\n      left: 10px;\n      opacity: 0.0;\n    }\n\n    md-spinner.show[_ngcontent-%COMP%] {\n      opacity: 1.0;\n    }'];
var renderType_BookSearchComponent:import0.RenderComponentType = (null as any);
class _View_BookSearchComponent0 extends import1.AppView<import3.BookSearchComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _MdCard_1_4:import10.MdCard;
  _text_2:any;
  _el_3:any;
  _MdCardTitle_3_3:import10.MdCardTitle;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _MdCardContent_6_3:import10.MdCardContent;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _MdInput_8_4:import11.MdInput;
  __NG_VALUE_ACCESSOR_8_5:any[];
  _query_MdPlaceholder_8_0:import12.QueryList<any>;
  _query_MdHint_8_1:import12.QueryList<any>;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _MdSpinner_10_4:import13.MdSpinner;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookSearchComponent0,renderType_BookSearchComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_8_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_8_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_8_5 = [this._MdInput_8_4]); }
    return this.__NG_VALUE_ACCESSOR_8_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'md-card',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import14.viewFactory_MdCard0(this.viewUtils,this.injector(1),this._appEl_1);
    this._MdCard_1_4 = new import10.MdCard();
    this._appEl_1.initComponent(this._MdCard_1_4,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'md-card-title',(null as any));
    this._MdCardTitle_3_3 = new import10.MdCardTitle();
    this._text_4 = this.renderer.createText(this._el_3,'Find a Book',(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'md-card-content',(null as any));
    this._MdCardContent_6_3 = new import10.MdCardContent();
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_8,'placeholder','Search for a book');
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import15.viewFactory_MdInput0(this.viewUtils,this.injector(8),this._appEl_8);
    this._MdInput_8_4 = new import11.MdInput();
    this._query_MdPlaceholder_8_0 = new import12.QueryList<any>();
    this._query_MdHint_8_1 = new import12.QueryList<any>();
    this._appEl_8.initComponent(this._MdInput_8_4,([] as any[]),compView_8);
    this._query_MdPlaceholder_8_0.reset(([] as any[]));
    this._MdInput_8_4._placeholderChild = this._query_MdPlaceholder_8_0.first;
    compView_8.create(this._MdInput_8_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_6,'md-spinner',(null as any));
    this.renderer.setElementAttribute(this._el_10,'mode','indeterminate');
    this.renderer.setElementAttribute(this._el_10,'role','progressbar');
    this._appEl_10 = new import2.AppElement(10,6,this,this._el_10);
    var compView_10:any = import16.viewFactory_MdSpinner0(this.viewUtils,this.injector(10),this._appEl_10);
    this._MdSpinner_10_4 = new import13.MdSpinner(compView_10.ref);
    this._appEl_10.initComponent(this._MdSpinner_10_4,([] as any[]),compView_10);
    compView_10.create(this._MdSpinner_10_4,([] as any[]),(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_1.create(this._MdCard_1_4,[([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_5,
        this._el_6,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'keyup',this.eventHandler(this._handle_keyup_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.MdCardTitle) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._MdCardTitle_3_3; }
    if (((token === import11.MdInput) && (8 === requestNodeIndex))) { return this._MdInput_8_4; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (8 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_8_5; }
    if (((token === import13.MdSpinner) && (10 === requestNodeIndex))) { return this._MdSpinner_10_4; }
    if (((token === import10.MdCardContent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdCardContent_6_3; }
    if (((token === import10.MdCard) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MdCard_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = 'Search for a book';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MdInput_8_4.placeholder = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['placeholder'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.query;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MdInput_8_4.value = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['value'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._MdInput_8_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_8_1.dirty) {
        this._query_MdHint_8_1.reset(([] as any[]));
        this._MdInput_8_4._hintChildren = this._query_MdHint_8_1;
        this._query_MdHint_8_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_8_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._MdInput_8_4._align;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementAttribute(this._el_8,'align',((currVal_4 == (null as any))? (null as any): currVal_4.toString()));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.searching;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_10,'show',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_keyup_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.search.emit($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_1($event:any):boolean {
    this._appEl_8.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_8_4.focus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_BookSearchComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.BookSearchComponent> {
  if ((renderType_BookSearchComponent === (null as any))) { (renderType_BookSearchComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_BookSearchComponent,{})); }
  return new _View_BookSearchComponent0(viewUtils,parentInjector,declarationEl);
}