/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './book-preview-list';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/common/src/directives/ng_for';
import * as import11 from '@angular/core/src/linker/template_ref';
import * as import12 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import13 from './book-preview';
import * as import14 from './book-preview.ngfactory';
var renderType_BookPreviewListComponent_Host:import0.RenderComponentType = (null as any);
class _View_BookPreviewListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BookPreviewListComponent_0_4:import3.BookPreviewListComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewListComponent_Host0,renderType_BookPreviewListComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-book-preview-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_BookPreviewListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BookPreviewListComponent_0_4 = new import3.BookPreviewListComponent();
    this._appEl_0.initComponent(this._BookPreviewListComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._BookPreviewListComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.BookPreviewListComponent) && (0 === requestNodeIndex))) { return this._BookPreviewListComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_BookPreviewListComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_BookPreviewListComponent_Host === (null as any))) { (renderType_BookPreviewListComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_BookPreviewListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const BookPreviewListComponentNgFactory:import9.ComponentFactory<import3.BookPreviewListComponent> = new import9.ComponentFactory<import3.BookPreviewListComponent>('bc-book-preview-list',viewFactory_BookPreviewListComponent_Host0,import3.BookPreviewListComponent);
const styles_BookPreviewListComponent:any[] = ['[_nghost-%COMP%] {\n      display: flex;\n      flex-wrap: wrap;\n      justify-content: center;\n    }'];
var renderType_BookPreviewListComponent:import0.RenderComponentType = (null as any);
class _View_BookPreviewListComponent0 extends import1.AppView<import3.BookPreviewListComponent> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _TemplateRef_1_5:any;
  _NgFor_1_6:import10.NgFor;
  _text_2:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewListComponent0,renderType_BookPreviewListComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import11.TemplateRef_(this._appEl_1,viewFactory_BookPreviewListComponent1);
    this._NgFor_1_6 = new import10.NgFor(this._appEl_1.vcRef,this._TemplateRef_1_5,this.parentInjector.get(import12.IterableDiffers),this.ref);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._anchor_1,
      this._text_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import10.NgFor) && (1 === requestNodeIndex))) { return this._NgFor_1_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.books;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_1_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_1_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_1_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_BookPreviewListComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.BookPreviewListComponent> {
  if ((renderType_BookPreviewListComponent === (null as any))) { (renderType_BookPreviewListComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_BookPreviewListComponent,{})); }
  return new _View_BookPreviewListComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_BookPreviewListComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BookPreviewComponent_0_4:import13.BookPreviewComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BookPreviewListComponent1,renderType_BookPreviewListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'bc-book-preview',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import14.viewFactory_BookPreviewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BookPreviewComponent_0_4 = new import13.BookPreviewComponent();
    this._appEl_0.initComponent(this._BookPreviewComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._BookPreviewComponent_0_4,([] as any[]),(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.BookPreviewComponent) && (0 === requestNodeIndex))) { return this._BookPreviewComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._BookPreviewComponent_0_4.book = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_BookPreviewListComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_BookPreviewListComponent1(viewUtils,parentInjector,declarationEl);
}