/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './layout';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/material/sidenav/sidenav';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '../../node_modules/@angular/material/sidenav/sidenav.ngfactory';
import * as import13 from '@angular/material/core/rtl/dir';
import * as import14 from '@angular/core/src/linker/element_ref';
var renderType_LayoutComponent_Host:import0.RenderComponentType = (null as any);
class _View_LayoutComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LayoutComponent_0_4:import3.LayoutComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LayoutComponent_Host0,renderType_LayoutComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-layout',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LayoutComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LayoutComponent_0_4 = new import3.LayoutComponent();
    this._appEl_0.initComponent(this._LayoutComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._LayoutComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LayoutComponent) && (0 === requestNodeIndex))) { return this._LayoutComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LayoutComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LayoutComponent_Host === (null as any))) { (renderType_LayoutComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LayoutComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LayoutComponentNgFactory:import9.ComponentFactory<import3.LayoutComponent> = new import9.ComponentFactory<import3.LayoutComponent>('bc-layout',viewFactory_LayoutComponent_Host0,import3.LayoutComponent);
const styles_LayoutComponent:any[] = ['md-sidenav-layout[_ngcontent-%COMP%] {\n      background: rgba(0, 0, 0, 0.03);\n    }\n    \n    *[_ngcontent-%COMP%],   * {\n      -webkit-font-smoothing: antialiased;\n      -moz-osx-font-smoothing: grayscale;\n    }'];
var renderType_LayoutComponent:import0.RenderComponentType = (null as any);
class _View_LayoutComponent0 extends import1.AppView<import3.LayoutComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _MdSidenavLayout_1_4:import10.MdSidenavLayout;
  _query_MdSidenav_1_0:import11.QueryList<any>;
  _text_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LayoutComponent0,renderType_LayoutComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'md-sidenav-layout',(null as any));
    this.renderer.setElementAttribute(this._el_1,'fullscreen','');
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import12.viewFactory_MdSidenavLayout0(this.viewUtils,this.injector(1),this._appEl_1);
    this._MdSidenavLayout_1_4 = new import10.MdSidenavLayout(this.parentInjector.get(import13.Dir,(null as any)),new import14.ElementRef(this._el_1),this.renderer);
    this._query_MdSidenav_1_0 = new import11.QueryList<any>();
    this._appEl_1.initComponent(this._MdSidenavLayout_1_4,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n      \n      ',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    compView_1.create(this._MdSidenavLayout_1_4,[
      ([] as any[]),
      ([] as any[]).concat([this._text_2]).concat(this.projectableNodes[0]).concat([this._text_3])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.MdSidenavLayout) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdSidenavLayout_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdSidenav_1_0.dirty) {
        this._query_MdSidenav_1_0.reset(([] as any[]));
        this._MdSidenavLayout_1_4._sidenavs = this._query_MdSidenav_1_0;
        this._query_MdSidenav_1_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdSidenavLayout_1_4.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_LayoutComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LayoutComponent> {
  if ((renderType_LayoutComponent === (null as any))) { (renderType_LayoutComponent = viewUtils.createRenderComponentType('',1,import8.ViewEncapsulation.Emulated,styles_LayoutComponent,{})); }
  return new _View_LayoutComponent0(viewUtils,parentInjector,declarationEl);
}