/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './sidenav';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/material/sidenav/sidenav';
import * as import11 from '@angular/material/list/list';
import * as import12 from '../../node_modules/@angular/material/sidenav/sidenav.ngfactory';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '../../node_modules/@angular/material/list/list.ngfactory';
var renderType_SidenavComponent_Host:import0.RenderComponentType = (null as any);
class _View_SidenavComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SidenavComponent_0_4:import3.SidenavComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SidenavComponent_Host0,renderType_SidenavComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('bc-sidenav',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SidenavComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SidenavComponent_0_4 = new import3.SidenavComponent();
    this._appEl_0.initComponent(this._SidenavComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._SidenavComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SidenavComponent) && (0 === requestNodeIndex))) { return this._SidenavComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SidenavComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SidenavComponent_Host === (null as any))) { (renderType_SidenavComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SidenavComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SidenavComponentNgFactory:import9.ComponentFactory<import3.SidenavComponent> = new import9.ComponentFactory<import3.SidenavComponent>('bc-sidenav',viewFactory_SidenavComponent_Host0,import3.SidenavComponent);
const styles_SidenavComponent:any[] = ['md-sidenav[_ngcontent-%COMP%] {\n      width: 300px;\n    }'];
var renderType_SidenavComponent:import0.RenderComponentType = (null as any);
class _View_SidenavComponent0 extends import1.AppView<import3.SidenavComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _MdSidenav_1_4:import10.MdSidenav;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _MdList_3_4:import11.MdList;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SidenavComponent0,renderType_SidenavComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'md-sidenav',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import12.viewFactory_MdSidenav0(this.viewUtils,this.injector(1),this._appEl_1);
    this._MdSidenav_1_4 = new import10.MdSidenav(new import13.ElementRef(this._el_1));
    this._appEl_1.initComponent(this._MdSidenav_1_4,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'md-nav-list',(null as any));
    this.renderer.setElementAttribute(this._el_3,'role','list');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import14.viewFactory_MdList0(this.viewUtils,this.injector(3),this._appEl_3);
    this._MdList_3_4 = new import11.MdList();
    this._appEl_3.initComponent(this._MdList_3_4,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_3.create(this._MdList_3_4,[([] as any[]).concat([this._text_4]).concat(this.projectableNodes[0]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_1.create(this._MdSidenav_1_4,[([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_6
      ]
    )],(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'transitionend',this.eventHandler(this._handle_transitionend_1_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdList) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdList_3_4; }
    if (((token === import10.MdSidenav) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._MdSidenav_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = this.context.open;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._MdSidenav_1_4.opened = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_1.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = (null as any);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementAttribute(this._el_1,'align',((currVal_2 == (null as any))? (null as any): currVal_2.toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._MdSidenav_1_4._isClosing;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-closing',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._MdSidenav_1_4._isOpening;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-opening',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._MdSidenav_1_4._isClosed;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-closed',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._MdSidenav_1_4._isOpened;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-opened',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._MdSidenav_1_4._isEnd;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-end',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._MdSidenav_1_4._modeSide;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-side',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._MdSidenav_1_4._modeOver;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-over',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._MdSidenav_1_4._modePush;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_1,'md-sidenav-push',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_transitionend_1_0($event:any):boolean {
    this._appEl_1.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdSidenav_1_4._onTransitionEnd($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SidenavComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SidenavComponent> {
  if ((renderType_SidenavComponent === (null as any))) { (renderType_SidenavComponent = viewUtils.createRenderComponentType('',1,import8.ViewEncapsulation.Emulated,styles_SidenavComponent,{})); }
  return new _View_SidenavComponent0(viewUtils,parentInjector,declarationEl);
}